function Fx = computeFx(x)
    Fx = [0 0 -x(4)*sin(x(3))-x(5)*cos(x(3)) cos(x(3)) -sin(x(3)) 0;...
          0 0 x(4)*cos(x(3))-x(5)*sin(x(3))  sin(x(3))  cos(x(3)) 0;...
          0 0               0                   0           0     1;...
          0 0               0                   0           0     0;...
          0 0               0                   0           0     0;...
          0 0               0                   0           0     0];
end